apiVersion: v1
kind: Template
metadata:
  name: manageiq-secrets
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: manageiq-secrets
    labels:
      app: manageiq
  stringData:
    admin-password: "${APPLICATION_ADMIN_PASSWORD}"
    encryption-key: "${ENCRYPTION_KEY}"
parameters:
- name: APPLICATION_ADMIN_PASSWORD
  value: smartvm
- name: ENCRYPTION_KEY
  from: "[a-zA-Z0-9]{43}"
  generate: expression
