apiVersion: v1
kind: Template
metadata:
  name: rbac
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: "${APP_NAME}-orchestrator"
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: "${APP_NAME}-anyuid"
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: "${APP_NAME}-httpd"
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: view
  roleRef:
    kind: ClusterRole
    name: view
    apiGroup: rbac.authorization.k8s.io
  subjects:
  - kind: ServiceAccount
    name: "${APP_NAME}-orchestrator"
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: edit
  roleRef:
    kind: ClusterRole
    name: edit
    apiGroup: rbac.authorization.k8s.io
  subjects:
  - kind: ServiceAccount
    name: "${APP_NAME}-orchestrator"
parameters:
- name: APP_NAME
  value: manageiq
